window.siteData = {
  brand: {
    name: "版纳人家",
    englishName: "Banna Renjia",
    tagline: "设计师美学 · 雨林景观 · 避世静谧度假民宿",
    location: "西双版纳 · 保利雨林澜山 · 傣王宫旧址半山",
    wechat: "woohhhoow",
    phone: "13309135639",
    heroImage: "assets/images/1706/微信图片_20260307175459_60_1.jpg",
    description:
      "版纳人家位于西双版纳保利雨林澜山，傣王宫旧址半山之上。这里远离告庄的热闹与喧嚣，以安静社区、雨林景观、湿地公园和设计师审美，承接一段更慢、更轻、更有空气感的版纳停留。",
  },
  nav: [
    { label: "首页", target: "#top" },
    { label: "理念", target: "#story" },
    { label: "房间", target: "#rooms" },
    { label: "雨林", target: "#landscape" },
    { label: "图库", target: "#gallery" },
    { label: "联系", target: "#contact" },
  ],
  rooms: [
    {
      id: "room-1701",
      roomNumber: "1701",
      title: "雨林景观大床房",
      view: "雨林 / 半山景观",
      capacity: "适合 1-2 人",
      tags: ["大床", "雨林景观", "安静休息", "可连住"],
      cover: "assets/images/1701/微信图片_20260307175156_22_1.jpg",
      description: "适合情侣、独自休息或短途度假，以安静窗景和舒展尺度承接版纳的湿润日常。",
    },
    {
      id: "room-1703",
      roomNumber: "1703",
      title: "半山静谧套房",
      view: "半山 / 社区绿意",
      capacity: "适合 2 人",
      tags: ["套房", "连住友好", "半山社区", "拍照友好"],
      cover: "assets/images/1703/微信图片_20260307175425_40_1.jpg",
      description: "更完整的空间尺度，适合希望停留更久、也更在意房间氛围的住客。",
    },
    {
      id: "room-1704",
      roomNumber: "1704",
      title: "江景度假房",
      view: "江景 / 雨林远眺",
      capacity: "适合 1-2 人",
      tags: ["江景", "度假感", "情侣", "轻松抵达"],
      cover: "assets/images/1704/微信图片_20260307175433_45_1.jpg",
      description: "把视线留给远处的江面与绿意，适合把行程放慢、把房间当作度假核心的人。",
    },
    {
      id: "room-1705",
      roomNumber: "1705",
      title: "同层连住房",
      view: "社区绿意 / 城市度假",
      capacity: "适合 2-3 人",
      tags: ["同层需求", "朋友出行", "家庭友好", "可沟通连住"],
      cover: "assets/images/1705/微信图片_20260307175447_51_1.jpg",
      description: "适合朋友结伴、家庭分房或需要同层沟通的入住方式，具体房态可通过微信提前确认。",
    },
    {
      id: "room-1706",
      roomNumber: "1706",
      title: "家庭友好房",
      view: "雨林 / 公园湿地",
      capacity: "适合 2-4 人",
      tags: ["家庭友好", "多人入住", "行李友好", "雨林氛围"],
      cover: "assets/images/1706/微信图片_20260307175510_64_1.jpg",
      description: "适合亲子、小家庭或朋友小团体，强调舒适休息、行李展开和清晰生活动线。",
    },
  ],
  landscape: [
    { title: "Half-Mountain", label: "傣王宫旧址半山", text: "半山尺度让景观更开阔，也让停留远离核心喧嚣。" },
    { title: "Wetland", label: "公园湿地景观", text: "公园、湿地与雨林动线自然交织，形成更松弛的版纳日常。" },
    { title: "Quiet Community", label: "安静社区环境", text: "小区里的多房间民宿集合，强调安静、秩序与可沟通的入住安排。" },
  ],
  experiences: [
    { icon: "01", title: "智能门锁自助入住", text: "确认房态后按指引自助入住，抵达更从容。" },
    { icon: "02", title: "本地管家支持", text: "抵达建议、连住安排与同层需求可通过微信沟通。" },
    { icon: "03", title: "入住前专业清洁", text: "入住前完成清洁与基础检查，让房间状态稳定可靠。" },
    { icon: "04", title: "连住 / 同层可沟通", text: "适合家庭、朋友和旅居客，提前说明需求便于匹配。" },
    { icon: "05", title: "行李友好", text: "社区接驳与观光电梯让带行李抵达更轻松。" },
    { icon: "06", title: "安静休息", text: "远离告庄喧嚣，适合睡眠、阅读、拍照和慢节奏度假。" },
  ],
  gallery: [
    { src: "assets/images/1706/微信图片_20260307175459_60_1.jpg", title: "雨林度假窗景", category: "rooms", caption: "真实房间照片，保留首屏雨林氛围。", size: "large" },
    { src: "assets/images/1701/微信图片_2026-03-07_180312_562.jpg", title: "1701 室内细节", category: "rooms", caption: "大床房细节与休息尺度。", size: "regular" },
    { src: "assets/images/1703/微信图片_20260307175223_33_1.jpg", title: "1703 半山套房", category: "rooms", caption: "适合连住与舒展停留的空间。", size: "tall" },
    { src: "assets/images/1704/微信图片_20260307175431_44_1.jpg", title: "1704 江景氛围", category: "views", caption: "江景与绿意形成轻松的度假感。", size: "regular" },
    { src: "assets/images/1705/微信图片_20260307175448_52_1.jpg", title: "1705 同层连住", category: "rooms", caption: "适合朋友与家庭灵活组合。", size: "wide" },
    { src: "assets/images/1706/微信图片_20260307175520_69_1.jpg", title: "家庭友好空间", category: "family", caption: "适合多人入住与行李展开。", size: "regular" },
    { src: "assets/images/1703/微信图片_20260307175419_36_1.jpg", title: "空间材质", category: "details", caption: "用克制细节表达设计感。", size: "regular" },
    { src: "assets/images/1704/微信图片_20260307175444_49_1.jpg", title: "窗边时刻", category: "views", caption: "把房间当作旅途中的停留地。", size: "tall" },
    { src: "assets/images/1705/微信图片_20260307175457_58_1.jpg", title: "轻松抵达", category: "family", caption: "适合朋友结伴与家庭出行。", size: "wide" },
  ],
  contact: {
    wechat: "woohhhoow",
    phone: "13309135639",
    inquiryPrompt: "咨询时请备注：入住日期 + 人数 + 是否需要连住 / 同层。",
  },
};
