window.BannaData = {
  brand: {
    name: "版纳人家",
    englishName: "Banna Renjia",
    tagline: "设计师美学、避世静谧、雨林景观度假民宿",
    type: "公寓楼 / 小区内的多房间民宿集合",
    location: "中国云南西双版纳景洪 · 保利雨林澜山 · 傣王宫旧址半山",
  },
  contact: {
    wechat: "woohhhoow",
    phone: "13309135639",
    inquiryPrompt: "入住日期 + 人数 + 是否需要连住 / 同层",
  },
  rooms: [
    {
      id: "rainforest-king",
      roomNumber: "01",
      title: "雨林景观大床房",
      area: "约 38-45 平方米",
      capacity: "适合 1-2 人",
      view: "雨林 / 半山绿意",
      tags: ["大床", "安静休息", "长住友好"],
      cover: "placeholder:rainforest",
      images: ["placeholder:rainforest", "placeholder:mist"],
      description: "适合情侣或独自停留，把清晨绿意、窗边阅读和慢节奏放进同一间房。",
      highlights: ["采光柔和", "适合阅读休息", "可咨询连住"],
      stayFit: "适合连住",
    },
    {
      id: "lancang-blue",
      roomNumber: "02",
      title: "澜江蓝调度假房",
      area: "约 40 平方米",
      capacity: "适合 1-2 人",
      view: "澜沧江蓝色意象",
      tags: ["江水氛围", "度假感", "情侣"],
      cover: "placeholder:river",
      images: ["placeholder:river", "placeholder:canopy"],
      description: "以澜沧江的蓝色流线为视觉线索，适合希望房间有轻松度假感的住客。",
      highlights: ["蓝色水线视觉", "安静舒展", "适合短住"],
      stayFit: "适合短住 / 连住",
    },
    {
      id: "half-mountain-suite",
      roomNumber: "03",
      title: "半山静谧套房",
      area: "约 48-55 平方米",
      capacity: "适合 2 人",
      view: "半山 / 社区绿意",
      tags: ["套房", "私密", "拍照友好"],
      cover: "placeholder:mountain",
      images: ["placeholder:mountain", "placeholder:leaf"],
      description: "更舒展的空间尺度，适合希望住得安静、留得更久，也在意设计氛围的人。",
      highlights: ["空间更舒展", "半山视线", "适合慢住"],
      stayFit: "适合连住",
    },
    {
      id: "same-floor-stay",
      roomNumber: "04",
      title: "同层连住组合",
      area: "按房态组合",
      capacity: "适合朋友 / 家庭",
      view: "小区绿意 / 便利动线",
      tags: ["同层需求", "连住", "朋友出行"],
      cover: "placeholder:terrace",
      images: ["placeholder:terrace", "placeholder:rainforest"],
      description: "适合朋友结伴、家庭分房或多日停留，同层与连住需求可提前通过微信沟通。",
      highlights: ["多人灵活安排", "可沟通同层", "适合家庭朋友"],
      stayFit: "同层需求可沟通",
    },
    {
      id: "family-friendly",
      roomNumber: "05",
      title: "家庭友好房",
      area: "约 45-60 平方米",
      capacity: "适合 2-4 人",
      view: "雨林 / 公园湿地",
      tags: ["家庭友好", "行李友好", "多人入住"],
      cover: "placeholder:family",
      images: ["placeholder:family", "placeholder:mist"],
      description: "面向亲子、小家庭和朋友小团体，强调抵达轻松、行李展开和清晰生活动线。",
      highlights: ["多人入住", "动线清楚", "行李友好"],
      stayFit: "适合家庭 / 连住",
    },
  ],
  experiences: [
    {
      icon: "key",
      title: "智能门锁自助入住",
      text: "确认入住后获得清晰抵达与自助入住指引，减少等待。",
    },
    {
      icon: "spark",
      title: "入住前专业清洁",
      text: "以住客可感知的整洁与安心为重点，抵达前完成房间准备。",
    },
    {
      icon: "quiet",
      title: "安静社区环境",
      text: "半山社区里的慢节奏停留，离热闹保持刚好的距离。",
    },
    {
      icon: "chat",
      title: "连住 / 同层可沟通",
      text: "日期、人数、连住与同层偏好可先通过微信确认。",
    },
    {
      icon: "guide",
      title: "本地管家支持",
      text: "抵达建议、房态确认和入住需求通过微信高效沟通。",
    },
    {
      icon: "bag",
      title: "行李友好",
      text: "适合情侣、家庭、朋友与长住度假等不同出行方式。",
    },
  ],
  gallery: [
    {
      id: "canopy-shadow",
      src: "placeholder:canopy",
      title: "雨林天幕",
      category: "rainforest",
      caption: "芭蕉叶与棕榈叶的深浅层次，像清晨走进雨林边缘。",
      size: "tall",
    },
    {
      id: "lancang-blue-line",
      src: "placeholder:river",
      title: "澜沧江蓝",
      category: "river",
      caption: "蓝色江水流线穿过半山空气，形成站点的视觉线索。",
      size: "wide",
    },
    {
      id: "half-mountain-ridge",
      src: "placeholder:mountain",
      title: "半山线条",
      category: "location",
      caption: "景洪半山、雨林轮廓和安静社区的抽象坐标。",
      size: "regular",
    },
    {
      id: "botanical-silhouette",
      src: "placeholder:leaf",
      title: "植物剪影",
      category: "rainforest",
      caption: "植物影子落在空间边缘，带来克制的热带气息。",
      size: "tall",
    },
    {
      id: "morning-mist",
      src: "placeholder:mist",
      title: "清晨雾气",
      category: "stay",
      caption: "柔和雾绿色承载清晨起居与窗边慢生活。",
      size: "regular",
    },
    {
      id: "same-floor-flow",
      src: "placeholder:terrace",
      title: "连住动线",
      category: "rooms",
      caption: "为同层、连住和多人出行保留清晰表达。",
      size: "wide",
    },
    {
      id: "family-soft-light",
      src: "placeholder:family",
      title: "家庭光线",
      category: "rooms",
      caption: "给家庭与朋友小团体预留更温和的视觉节奏。",
      size: "regular",
    },
    {
      id: "quiet-community",
      src: "placeholder:community",
      title: "安静社区",
      category: "location",
      caption: "不公开门牌，只表达抵达前需要理解的环境气质。",
      size: "tall",
    },
  ],
  galleryCategories: [
    { id: "all", label: "全部" },
    { id: "rainforest", label: "雨林" },
    { id: "river", label: "澜沧江" },
    { id: "rooms", label: "房间" },
    { id: "location", label: "位置" },
    { id: "stay", label: "入住" },
  ],
  locationPoints: [
    {
      title: "景洪",
      text: "西双版纳的城市生活与热带慢节奏在这里交汇。",
    },
    {
      title: "保利雨林澜山",
      text: "小区内多房间民宿集合，强调安静社区环境与抵达便利。",
    },
    {
      title: "傣王宫旧址半山",
      text: "以半山视线、雨林植物与江水蓝意象建立位置记忆。",
    },
    {
      title: "澜沧江与热带雨林",
      text: "用抽象流线和植物层表达环境，不展示普通地图截图。",
    },
  ],
  locationTimeline: [
    "微信确认房态、日期与入住人数",
    "确认后沟通抵达方式与小区接驳建议",
    "入住前完成专业清洁与房间准备",
    "按指引自助入住，享受安静半山假期",
  ],
  faq: [
    {
      question: "咨询时需要发什么信息？",
      answer: "请备注入住日期、人数、是否需要连住或同层，方便快速确认房态。",
    },
    {
      question: "可以电话联系吗？",
      answer: "可以。移动端可直接点击电话拨号，也建议通过微信保留日期与房态沟通记录。",
    },
    {
      question: "会公开具体门牌地址吗？",
      answer: "不会。确认入住后会通过微信发送清晰抵达与入住指引。",
    },
    {
      question: "适合朋友或家庭多间入住吗？",
      answer: "适合。请提前说明人数、房间数量和同层偏好，具体以当日房态为准。",
    },
  ],
};
